version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: speedmatch
      POSTGRES_USER: speedmatch
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - speedmatch-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U speedmatch -d speedmatch"]
      interval: 5s
      timeout: 5s
      retries: 5

  ktor-app:
    build:
      context: ../../
      dockerfile: container/dev/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/speedmatch
      DB_USER: speedmatch
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - speedmatch-network

volumes:
  postgres_data:

networks:
  speedmatch-network: