version: 0.0
os: linux
files:
  # デプロイスクリプト
  - source: deploy-scripts/
    destination: /home/ec2-user/speedmatch/
  # Docker Compose設定
  - source: container/
    destination: /home/ec2-user/speedmatch/container
  # appspec.yml自体
  - source: appspec-api.yml
    destination: /home/ec2-user/speedmatch/
  # ビルド済みJAR
  - source: 'api/build/libs/speed-match-card-game-api-all.jar'
    destination: /home/ec2-user/speedmatch/api/build/libs/
hooks:
  ApplicationStop:
    - location: deploy-scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy-scripts/start_application.sh
      timeout: 300
      runas: ec2-user