version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/speedmatch
hooks:
  ApplicationStop:
    - location: deploy-scripts/stop_application.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy-scripts/start_application.sh
      timeout: 300
      runas: ec2-user