version: 0.2

# AWS CodeBuild用ビルド仕様 - Backend (Ktor API)
# apiディレクトリのKotlin+Ktorアプリをビルド
# Gradle Shadowプラグインで実行可能なFat JARを作成

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Java dependencies..."
      - cd api
      - chmod +x gradlew
      
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - java --version
      - ./gradlew --version
      - echo "Build started on `date`"
      
  build:
    commands:
      - echo "Building Ktor application and creating Fat JAR..."
      - ./gradlew clean buildFatJar -x test
      - echo "Build completed on `date`"
      
  post_build:
    commands:
      - echo "Preparing artifacts..."
      - ls -la build/libs/
      - echo "Backend build finished"

artifacts:
  files:
    - 'api/build/libs/speed-match-card-game-api-all.jar'  # Fat JARのみを含める
    - 'container/**/*'          # Docker関連ファイルを含める
    - 'appspec-api.yml'       # appspec.ymlを含める
    - 'deploy-scripts/**/*'  # デプロイスクリプトを含める'
  base-directory: './'
  name: speedmatch-backend

cache:
  paths:
    - 'api/.gradle/**/*'
    - 'api/build/**/*'
